print ("hello there do you want to hear a joke")
input ("")
print ("why did the chicken cross the road")
input ("") 
print ("to get to the other side")
input ("")
print ("my name is bob and i think i have an even more funny joke do you want hear it?")
input ("")
print ("great your gonna laugh your butt off")
input("")
print("why was the fish scared to play basketball")
input("")
print ("because its afraid of the net")
input("")
print ("you think thats funny you haven't seen my best work ")
input('')
print ("you reading a book about gravity and its impossible to put down")
print("i know your about to die laughing inside so ill leave u at that")